apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: amq-stream
  namespace: amq-stream
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
  - amq-stream
