apiVersion: v1
kind: Namespace
metadata:
  name: amq
  labels:
    kubernetes.io/metadata.name: amq
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/description: ''
    openshift.io/display-name: ''
