apiVersion: v1
kind: Secret
metadata:
  name: properties-jaas-config-alternative
  namespace: amq
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
data:
  artemis-users.properties: YWRtaW49YWRtaW4xMjM0CnVzZXIxPXBhc3N3b3JkMTIzCnB1Ymxpc2hlcj1wdWJwYXNz
  artemis-roles.properties: YW1xPWFkbWluCmFkbWlucz1hZG1pbgp1c2Vycz11c2VyMSxwdWJsaXNoZXI=