apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: broker-persistent
  namespace: amq
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  acceptors:
    - expose: false
      name: amqp-acceptors
      port: 5672
      protocols: 'amqp,core'
  brokerProperties:
    - securityRoles.#.app.send=true
    - securityRoles.#.app.consume=true
    - securityRoles.#.app.createAddress=true
    - securityRoles.#.app.createNonDurableQueue=true
    - securityRoles.#.app.deleteNonDurableQueue=true
    - securityRoles.#.app.createDurableQueue=true
    - securityRoles.#.app.deleteDurableQueue=true
    - securityRoles.#.app.deleteAddress=true
    - securityRoles.#.admin.manage=true
    - securityRoles.#.app.browse=true
  console:
    expose: false
  deploymentPlan:
    size: 2
    persistenceEnabled: true
    requireLogin: false
    messageMigration: true
    extraMounts:
      secrets:
        - properties-jaas-config
    managementRBACEnabled: true
    journalType: nio
    enableMetricsPlugin: true
    jolokiaAgentEnabled: false
    image: placeholder
    storage:
      size: 3Gi
      storageClassName: thin-csi
