apiVersion: v1
kind: Secret
metadata:
  name: properties-jaas-config
  namespace: amq
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  login.config: |
    activemq {
        org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule required
            debug=false
            reload=true
            org.apache.activemq.jaas.properties.user="artemis-users.properties"
            org.apache.activemq.jaas.properties.role="artemis-roles.properties";
    };
  artemis-users.properties: |
    admin=admin1234
    user1=password123
    publisher=pubpass
  artemis-roles.properties: |
    amq=admin
    admins=admin
    users=user1,publisher
